# Generated by Django 5.1 on 2024-08-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beading_butiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimlar',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
