# Generated by Django 5.1 on 2024-08-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beading_butiki', '0002_xodimlar_address_xodimlar_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='davomat',
            old_name='sana',
            new_name='date',
        ),
        migrations.AddField(
            model_name='davomat',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
