# Generated by Django 5.1 on 2024-08-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beading_butiki', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='xodimlar',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
