# Generated by Django 5.1 on 2024-08-10 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beading_butiki', '0005_remove_profile_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='davomat',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='xodimlar',
            name='profile_picture',
        ),
    ]
